// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

#ifndef PROTOBUF_Request_2eproto__INCLUDED
#define PROTOBUF_Request_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace c4 {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Request_2eproto();
void protobuf_AssignDesc_Request_2eproto();
void protobuf_ShutdownFile_Request_2eproto();

class Request;
class Request_CompilationUnit;

enum Request_Action {
  Request_Action_PROJECT = 0,
  Request_Action_COMPILE = 1
};
bool Request_Action_IsValid(int value);
const Request_Action Request_Action_Action_MIN = Request_Action_PROJECT;
const Request_Action Request_Action_Action_MAX = Request_Action_COMPILE;
const int Request_Action_Action_ARRAYSIZE = Request_Action_Action_MAX + 1;

const ::google::protobuf::EnumDescriptor* Request_Action_descriptor();
inline const ::std::string& Request_Action_Name(Request_Action value) {
  return ::google::protobuf::internal::NameOfEnum(
    Request_Action_descriptor(), value);
}
inline bool Request_Action_Parse(
    const ::std::string& name, Request_Action* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Request_Action>(
    Request_Action_descriptor(), name, value);
}
// ===================================================================

class Request_CompilationUnit : public ::google::protobuf::Message {
 public:
  Request_CompilationUnit();
  virtual ~Request_CompilationUnit();

  Request_CompilationUnit(const Request_CompilationUnit& from);

  inline Request_CompilationUnit& operator=(const Request_CompilationUnit& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request_CompilationUnit& default_instance();

  void Swap(Request_CompilationUnit* other);

  // implements Message ----------------------------------------------

  Request_CompilationUnit* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request_CompilationUnit& from);
  void MergeFrom(const Request_CompilationUnit& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string filename = 1;
  inline bool has_filename() const;
  inline void clear_filename();
  static const int kFilenameFieldNumber = 1;
  inline const ::std::string& filename() const;
  inline void set_filename(const ::std::string& value);
  inline void set_filename(const char* value);
  inline void set_filename(const char* value, size_t size);
  inline ::std::string* mutable_filename();
  inline ::std::string* release_filename();
  inline void set_allocated_filename(::std::string* filename);

  // required string buffer = 2;
  inline bool has_buffer() const;
  inline void clear_buffer();
  static const int kBufferFieldNumber = 2;
  inline const ::std::string& buffer() const;
  inline void set_buffer(const ::std::string& value);
  inline void set_buffer(const char* value);
  inline void set_buffer(const char* value, size_t size);
  inline ::std::string* mutable_buffer();
  inline ::std::string* release_buffer();
  inline void set_allocated_buffer(::std::string* buffer);

  // @@protoc_insertion_point(class_scope:c4.Request.CompilationUnit)
 private:
  inline void set_has_filename();
  inline void clear_has_filename();
  inline void set_has_buffer();
  inline void clear_has_buffer();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* filename_;
  ::std::string* buffer_;
  friend void  protobuf_AddDesc_Request_2eproto();
  friend void protobuf_AssignDesc_Request_2eproto();
  friend void protobuf_ShutdownFile_Request_2eproto();

  void InitAsDefaultInstance();
  static Request_CompilationUnit* default_instance_;
};
// -------------------------------------------------------------------

class Request : public ::google::protobuf::Message {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  void Swap(Request* other);

  // implements Message ----------------------------------------------

  Request* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Request_CompilationUnit CompilationUnit;

  typedef Request_Action Action;
  static const Action PROJECT = Request_Action_PROJECT;
  static const Action COMPILE = Request_Action_COMPILE;
  static inline bool Action_IsValid(int value) {
    return Request_Action_IsValid(value);
  }
  static const Action Action_MIN =
    Request_Action_Action_MIN;
  static const Action Action_MAX =
    Request_Action_Action_MAX;
  static const int Action_ARRAYSIZE =
    Request_Action_Action_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Action_descriptor() {
    return Request_Action_descriptor();
  }
  static inline const ::std::string& Action_Name(Action value) {
    return Request_Action_Name(value);
  }
  static inline bool Action_Parse(const ::std::string& name,
      Action* value) {
    return Request_Action_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .c4.Request.Action action = 1;
  inline bool has_action() const;
  inline void clear_action();
  static const int kActionFieldNumber = 1;
  inline ::c4::Request_Action action() const;
  inline void set_action(::c4::Request_Action value);

  // required string projectId = 2;
  inline bool has_projectid() const;
  inline void clear_projectid();
  static const int kProjectIdFieldNumber = 2;
  inline const ::std::string& projectid() const;
  inline void set_projectid(const ::std::string& value);
  inline void set_projectid(const char* value);
  inline void set_projectid(const char* value, size_t size);
  inline ::std::string* mutable_projectid();
  inline ::std::string* release_projectid();
  inline void set_allocated_projectid(::std::string* projectid);

  // optional .c4.Request.CompilationUnit unit = 3;
  inline bool has_unit() const;
  inline void clear_unit();
  static const int kUnitFieldNumber = 3;
  inline const ::c4::Request_CompilationUnit& unit() const;
  inline ::c4::Request_CompilationUnit* mutable_unit();
  inline ::c4::Request_CompilationUnit* release_unit();
  inline void set_allocated_unit(::c4::Request_CompilationUnit* unit);

  // @@protoc_insertion_point(class_scope:c4.Request)
 private:
  inline void set_has_action();
  inline void clear_has_action();
  inline void set_has_projectid();
  inline void clear_has_projectid();
  inline void set_has_unit();
  inline void clear_has_unit();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* projectid_;
  ::c4::Request_CompilationUnit* unit_;
  int action_;
  friend void  protobuf_AddDesc_Request_2eproto();
  friend void protobuf_AssignDesc_Request_2eproto();
  friend void protobuf_ShutdownFile_Request_2eproto();

  void InitAsDefaultInstance();
  static Request* default_instance_;
};
// ===================================================================


// ===================================================================

// Request_CompilationUnit

// required string filename = 1;
inline bool Request_CompilationUnit::has_filename() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request_CompilationUnit::set_has_filename() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request_CompilationUnit::clear_has_filename() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request_CompilationUnit::clear_filename() {
  if (filename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filename_->clear();
  }
  clear_has_filename();
}
inline const ::std::string& Request_CompilationUnit::filename() const {
  // @@protoc_insertion_point(field_get:c4.Request.CompilationUnit.filename)
  return *filename_;
}
inline void Request_CompilationUnit::set_filename(const ::std::string& value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
  // @@protoc_insertion_point(field_set:c4.Request.CompilationUnit.filename)
}
inline void Request_CompilationUnit::set_filename(const char* value) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filename_ = new ::std::string;
  }
  filename_->assign(value);
  // @@protoc_insertion_point(field_set_char:c4.Request.CompilationUnit.filename)
}
inline void Request_CompilationUnit::set_filename(const char* value, size_t size) {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filename_ = new ::std::string;
  }
  filename_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:c4.Request.CompilationUnit.filename)
}
inline ::std::string* Request_CompilationUnit::mutable_filename() {
  set_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    filename_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:c4.Request.CompilationUnit.filename)
  return filename_;
}
inline ::std::string* Request_CompilationUnit::release_filename() {
  clear_has_filename();
  if (filename_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = filename_;
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Request_CompilationUnit::set_allocated_filename(::std::string* filename) {
  if (filename_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete filename_;
  }
  if (filename) {
    set_has_filename();
    filename_ = filename;
  } else {
    clear_has_filename();
    filename_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:c4.Request.CompilationUnit.filename)
}

// required string buffer = 2;
inline bool Request_CompilationUnit::has_buffer() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request_CompilationUnit::set_has_buffer() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request_CompilationUnit::clear_has_buffer() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request_CompilationUnit::clear_buffer() {
  if (buffer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_->clear();
  }
  clear_has_buffer();
}
inline const ::std::string& Request_CompilationUnit::buffer() const {
  // @@protoc_insertion_point(field_get:c4.Request.CompilationUnit.buffer)
  return *buffer_;
}
inline void Request_CompilationUnit::set_buffer(const ::std::string& value) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(value);
  // @@protoc_insertion_point(field_set:c4.Request.CompilationUnit.buffer)
}
inline void Request_CompilationUnit::set_buffer(const char* value) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(value);
  // @@protoc_insertion_point(field_set_char:c4.Request.CompilationUnit.buffer)
}
inline void Request_CompilationUnit::set_buffer(const char* value, size_t size) {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  buffer_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:c4.Request.CompilationUnit.buffer)
}
inline ::std::string* Request_CompilationUnit::mutable_buffer() {
  set_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    buffer_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:c4.Request.CompilationUnit.buffer)
  return buffer_;
}
inline ::std::string* Request_CompilationUnit::release_buffer() {
  clear_has_buffer();
  if (buffer_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = buffer_;
    buffer_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Request_CompilationUnit::set_allocated_buffer(::std::string* buffer) {
  if (buffer_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete buffer_;
  }
  if (buffer) {
    set_has_buffer();
    buffer_ = buffer;
  } else {
    clear_has_buffer();
    buffer_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:c4.Request.CompilationUnit.buffer)
}

// -------------------------------------------------------------------

// Request

// required .c4.Request.Action action = 1;
inline bool Request::has_action() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Request::set_has_action() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Request::clear_has_action() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Request::clear_action() {
  action_ = 0;
  clear_has_action();
}
inline ::c4::Request_Action Request::action() const {
  // @@protoc_insertion_point(field_get:c4.Request.action)
  return static_cast< ::c4::Request_Action >(action_);
}
inline void Request::set_action(::c4::Request_Action value) {
  assert(::c4::Request_Action_IsValid(value));
  set_has_action();
  action_ = value;
  // @@protoc_insertion_point(field_set:c4.Request.action)
}

// required string projectId = 2;
inline bool Request::has_projectid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Request::set_has_projectid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Request::clear_has_projectid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Request::clear_projectid() {
  if (projectid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    projectid_->clear();
  }
  clear_has_projectid();
}
inline const ::std::string& Request::projectid() const {
  // @@protoc_insertion_point(field_get:c4.Request.projectId)
  return *projectid_;
}
inline void Request::set_projectid(const ::std::string& value) {
  set_has_projectid();
  if (projectid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    projectid_ = new ::std::string;
  }
  projectid_->assign(value);
  // @@protoc_insertion_point(field_set:c4.Request.projectId)
}
inline void Request::set_projectid(const char* value) {
  set_has_projectid();
  if (projectid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    projectid_ = new ::std::string;
  }
  projectid_->assign(value);
  // @@protoc_insertion_point(field_set_char:c4.Request.projectId)
}
inline void Request::set_projectid(const char* value, size_t size) {
  set_has_projectid();
  if (projectid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    projectid_ = new ::std::string;
  }
  projectid_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:c4.Request.projectId)
}
inline ::std::string* Request::mutable_projectid() {
  set_has_projectid();
  if (projectid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    projectid_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:c4.Request.projectId)
  return projectid_;
}
inline ::std::string* Request::release_projectid() {
  clear_has_projectid();
  if (projectid_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = projectid_;
    projectid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Request::set_allocated_projectid(::std::string* projectid) {
  if (projectid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete projectid_;
  }
  if (projectid) {
    set_has_projectid();
    projectid_ = projectid;
  } else {
    clear_has_projectid();
    projectid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:c4.Request.projectId)
}

// optional .c4.Request.CompilationUnit unit = 3;
inline bool Request::has_unit() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Request::set_has_unit() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Request::clear_has_unit() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Request::clear_unit() {
  if (unit_ != NULL) unit_->::c4::Request_CompilationUnit::Clear();
  clear_has_unit();
}
inline const ::c4::Request_CompilationUnit& Request::unit() const {
  // @@protoc_insertion_point(field_get:c4.Request.unit)
  return unit_ != NULL ? *unit_ : *default_instance_->unit_;
}
inline ::c4::Request_CompilationUnit* Request::mutable_unit() {
  set_has_unit();
  if (unit_ == NULL) unit_ = new ::c4::Request_CompilationUnit;
  // @@protoc_insertion_point(field_mutable:c4.Request.unit)
  return unit_;
}
inline ::c4::Request_CompilationUnit* Request::release_unit() {
  clear_has_unit();
  ::c4::Request_CompilationUnit* temp = unit_;
  unit_ = NULL;
  return temp;
}
inline void Request::set_allocated_unit(::c4::Request_CompilationUnit* unit) {
  delete unit_;
  unit_ = unit;
  if (unit) {
    set_has_unit();
  } else {
    clear_has_unit();
  }
  // @@protoc_insertion_point(field_set_allocated:c4.Request.unit)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace c4

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::c4::Request_Action> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::c4::Request_Action>() {
  return ::c4::Request_Action_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Request_2eproto__INCLUDED
